name: 'cdc_gold'
version: '1.0.0'
profile: 'cdc_gold'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ write_dq_results() }}"

models:
  cdc_gold:
    +materialized: table
