"""
DV 2.0 Generator — Config & Query Template Generator (TASK_06)

Takes the classified DVModel (hubs + links + satellites from step2) and produces:
1. The full dv_model.json draft config (03_dv_model_draft.json)
2. Per-entity PySpark query snippet files in query_templates/
3. PIT and Bridge definitions added to the model

Reads from 02b_merged_classification.json if it exists, else falls back to
02_classification.json.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..models import DVModel, HubDef, LinkDef, SatDef, PitDef, BridgeDef
from ..session import Session
from .step2_rule_engine import _model_from_dict, _model_to_dict

# Hardcoded PIT and Bridge definitions from design/dv2/DV2_VAULT_LAYER_PLAN.md
DEFAULT_PIT_TABLES = [
    {
        "name": "PIT_FILM",
        "hub": "HUB_FILM",
        "satellites": ["SAT_FILM_CORE", "SAT_FILM_PRICING"],
        "snapshot_grain": "daily",
    },
    {
        "name": "PIT_RENTAL",
        "hub": "HUB_RENTAL",
        "satellites": ["SAT_RENTAL_CORE"],
        "snapshot_grain": "daily",
    },
    {
        "name": "PIT_CUSTOMER",
        "hub": "HUB_CUSTOMER",
        "satellites": ["SAT_CUSTOMER_CORE"],
        "snapshot_grain": "daily",
    },
    {
        "name": "PIT_PAYMENT",
        "hub": "HUB_PAYMENT",
        "satellites": ["SAT_PAYMENT_CORE", "SAT_PAYMENT_PRICING"],
        "snapshot_grain": "daily",
    },
]

DEFAULT_BRIDGE_TABLES = [
    {
        "name": "BRG_RENTAL_FILM",
        "path": [
            "HUB_RENTAL",
            "LNK_RENTAL_INVENTORY",
            "HUB_INVENTORY",
            "LNK_INVENTORY_FILM",
            "HUB_FILM",
        ],
    },
    {
        "name": "BRG_FILM_CAST",
        "path": ["HUB_FILM", "LNK_FILM_ACTOR", "HUB_ACTOR"],
    },
]

_SHARED_HASH_PY = '''\
# AUTO-GENERATED by dv_generator step3 — DO NOT EDIT MANUALLY
# Shared hash key and diff hash utility functions for DV 2.0 vault notebooks.

from pyspark.sql import functions as F


def hub_hash_expr(bk_col: str):
    """Return a PySpark Column expression for a hub hash key (SHA-256).

    Args:
        bk_col: Name of the business key column.

    Returns:
        PySpark Column: 64-char hex string.
    """
    return F.sha2(
        F.concat_ws("||", F.upper(F.trim(F.col(bk_col).cast("string")))),
        256,
    )


def diff_hash_expr(tracked_cols: list):
    """Return a PySpark Column expression for a satellite diff hash (SHA-256).

    Args:
        tracked_cols: List of column names to include in the hash.

    Returns:
        PySpark Column: 64-char hex string that changes whenever any tracked
        column changes.
    """
    return F.sha2(
        F.concat_ws(
            "||",
            *[F.coalesce(F.col(c).cast("string"), F.lit("NULL")) for c in tracked_cols],
        ),
        256,
    )
'''


class ArtifactGenerator:
    """Generates dv_model_draft.json and per-entity PySpark query templates."""

    def __init__(self, model: DVModel, session: Session) -> None:
        self.model = model
        self.session = session
        self.output_dir = session.session_dir
        self.templates_dir = session.session_dir / "query_templates"

    def run(self) -> DVModel:
        """Run artifact generation (or return cached model if step already done)."""
        if self.session.is_step_done("step3_artifact_gen"):
            return self._load_model()

        self._add_pit_and_bridge()
        self.templates_dir.mkdir(exist_ok=True)
        self._write_shared_hash()
        for hub in self.model.hubs:
            self._write_hub_template(hub)
        for lnk in self.model.links:
            self._write_link_template(lnk)
        for sat in self.model.satellites:
            self._write_sat_template(sat)
        self._write_model_json()

        self.session.mark_step_done(
            "step3_artifact_gen",
            metadata={
                "hubs": len(self.model.hubs),
                "links": len(self.model.links),
                "satellites": len(self.model.satellites),
                "pit_tables": len(self.model.pit_tables),
                "bridge_tables": len(self.model.bridge_tables),
            },
        )
        return self.model

    # ------------------------------------------------------------------
    # Model loading (with 02b fallback)
    # ------------------------------------------------------------------

    @classmethod
    def from_session(cls, session: Session) -> "ArtifactGenerator":
        """Load the DVModel from the session, preferring merged classification."""
        merged_path = session.session_dir / "02b_merged_classification.json"
        fallback_path = session.session_dir / "02_classification.json"
        source = merged_path if merged_path.exists() else fallback_path
        model = _model_from_dict(json.loads(source.read_text()))
        return cls(model, session)

    # ------------------------------------------------------------------
    # PIT and Bridge injection
    # ------------------------------------------------------------------

    def _add_pit_and_bridge(self) -> None:
        """Populate model.pit_tables and model.bridge_tables from defaults."""
        for p in DEFAULT_PIT_TABLES:
            self.model.pit_tables.append(
                PitDef(
                    name=p["name"],
                    target_table=f"vault.{p['name'].lower()}",
                    hub=p["hub"],
                    satellites=p["satellites"],
                    snapshot_grain=p.get("snapshot_grain", "daily"),
                    enabled=True,
                )
            )
        for b in DEFAULT_BRIDGE_TABLES:
            self.model.bridge_tables.append(
                BridgeDef(
                    name=b["name"],
                    target_table=f"vault.{b['name'].lower()}",
                    path=b["path"],
                    enabled=True,
                )
            )

    # ------------------------------------------------------------------
    # Template writers
    # ------------------------------------------------------------------

    def _write_shared_hash(self) -> None:
        """Write _shared_hash.py with canonical hash functions."""
        (self.templates_dir / "_shared_hash.py").write_text(_SHARED_HASH_PY)

    def _write_hub_template(self, hub: HubDef) -> None:
        """Write query_templates/hub_{lower_name}.py."""
        lower = hub.name.lower()  # e.g. hub_film
        bk_cols_expr = " F.upper(F.trim(F.col(c).cast(\"string\"))) for c in BUSINESS_KEYS"
        content = f"""\
# AUTO-GENERATED by dv_generator step3 — DO NOT EDIT MANUALLY
# Hub: {hub.name}  |  Source: {hub.source_table}

from pyspark.sql import functions as F

HASH_KEY_EXPR = F.sha2(
    F.concat_ws("||", F.upper(F.trim(F.col({hub.business_key_columns[0]!r}).cast("string")))),
    256,
).alias("HK_{hub.name[4:]}")

LOAD_DATE_COL = {hub.load_date_column!r}
RECORD_SOURCE  = {hub.record_source!r}
TARGET_TABLE   = {hub.target_table!r}
BUSINESS_KEYS  = {hub.business_key_columns!r}
ENABLED        = {hub.enabled!r}
"""
        (self.templates_dir / f"{lower}.py").write_text(content)

    def _write_link_template(self, lnk: LinkDef) -> None:
        """Write query_templates/lnk_{lower_name}.py."""
        lower = lnk.name.lower()  # e.g. lnk_rental_customer
        refs_repr = [
            {"hub": r.hub, "source_column": r.source_column}
            for r in lnk.hub_references
        ]
        # Build composite link hash from all FK columns
        fk_cols = [r.source_column for r in lnk.hub_references]
        hash_parts = ", ".join(
            f'F.upper(F.trim(F.col({c!r}).cast("string")))' for c in fk_cols
        )
        content = f"""\
# AUTO-GENERATED by dv_generator step3 — DO NOT EDIT MANUALLY
# Link: {lnk.name}  |  Source: {lnk.source_table}

from pyspark.sql import functions as F

LINK_HASH_EXPR = F.sha2(
    F.concat_ws("||", {hash_parts}),
    256,
).alias("HK_{lnk.name[4:]}")

LOAD_DATE_COL  = {lnk.load_date_column!r}
RECORD_SOURCE  = {lnk.record_source!r}
TARGET_TABLE   = {lnk.target_table!r}
HUB_REFERENCES = {refs_repr!r}
ENABLED        = {lnk.enabled!r}
"""
        (self.templates_dir / f"{lower}.py").write_text(content)

    def _write_sat_template(self, sat: SatDef) -> None:
        """Write query_templates/sat_{lower_name}.py with DIFF_HASH_EXPR and constants."""
        lower = sat.name.lower()  # e.g. sat_film_pricing
        # Build diff hash expression over tracked columns
        diff_parts = ", ".join(
            f'F.coalesce(F.col({c!r}).cast("string"), F.lit("NULL"))'
            for c in sat.tracked_columns
        )
        # Hub hash key expression (from hub BK source column)
        hub_hash = (
            f'F.sha2(F.concat_ws("||", F.upper(F.trim(F.col({sat.hub_key_source_column!r}).cast("string")))), 256)'
            if sat.hub_key_source_column
            else 'F.lit(None)'
        )
        content = f"""\
# AUTO-GENERATED by dv_generator step3 — DO NOT EDIT MANUALLY
# Satellite: {sat.name}  |  Parent Hub: {sat.parent_hub}  |  Source: {sat.source_table}

from pyspark.sql import functions as F

DIFF_HASH_EXPR = F.sha2(
    F.concat_ws("||", {diff_parts}),
    256,
).alias("DIFF_HK")

HUB_KEY_EXPR = {hub_hash}.alias("HK_{sat.parent_hub[4:]}")

TRACKED_COLUMNS = {sat.tracked_columns!r}
LOAD_DATE_COL   = {sat.load_date_column!r}
RECORD_SOURCE   = {sat.record_source!r}
TARGET_TABLE    = {sat.target_table!r}
PARENT_HUB      = {sat.parent_hub!r}
HUB_KEY_COL     = {sat.hub_key_source_column!r}
SPLIT_REASON    = {sat.split_reason!r}
ENABLED         = {sat.enabled!r}
"""
        (self.templates_dir / f"{lower}.py").write_text(content)

    # ------------------------------------------------------------------
    # Model JSON serialisation
    # ------------------------------------------------------------------

    def _write_model_json(self) -> None:
        """Serialise full DVModel to 03_dv_model_draft.json."""
        out_path = self.output_dir / "03_dv_model_draft.json"
        out_path.write_text(json.dumps(_model_to_dict(self.model), indent=2))

    def _load_model(self) -> DVModel:
        """Load cached model from 03_dv_model_draft.json."""
        draft_path = self.output_dir / "03_dv_model_draft.json"
        return _model_from_dict(json.loads(draft_path.read_text()))
